version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: "100"

networks:
  docker-network:
    driver: bridge

services:
  postgres_db:
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    networks:
      - docker-network
    logging: *default-logging

volumes:
  db-data:
